import { Geist, Geist_Mono } from "next/font/google";
import { Outfit } from 'next/font/google';
import "./globals.css";
import Navbar from "./common/navbar/Navbar";
import Footer from "./common/footer/Footer";
import BootomBar from "./common/bottomBar/BottomBar";

const outfit = Outfit({ subsets: ['latin'], weight: ["300", "400", "600", "700"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: " Luxeurs Shopping Online In Pakistan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.className} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
        <BootomBar/>
      </body>
    </html>
  );
}
